[supervisord]
nodaemon=true
silent=true
user=root
logfile=/dev/null
logfile_maxbytes=0

[inet_http_server]
port=127.0.0.1:9001

[program:app]
command=python /usr/src/app/main.py
autostart=true
autorestart=true
stopwaitsecs=120

stdout_logfile=/dev/null
stdout_logfile_maxbytes=0
stderr_logfile=/dev/null
stderr_logfile_maxbytes=0
stdout_events_enabled=true
stderr_events_enabled=true

[eventlistener:logging]
command = python /opt/supervisor_logging.py
events = PROCESS_LOG
environment = SYSLOG_SERVER="127.0.0.2", SYSLOG_PORT="514", SYSLOG_PROTO="tcp"

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface
