[supervisord]
nodaemon=true
silent=true
user=root
logfile=/dev/null
logfile_maxbytes=0

[inet_http_server]
port=127.0.0.1:9001

[program:app]
command=python /usr/src/app/main.py
autostart=true
autorestart=true
stopwaitsecs=120

stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
stdout_events_enabled=true
stderr_events_enabled=true

[eventlistener:log_forwarder]
command=python /opt/log_forwarder.py
events=PROCESS_LOG_STDOUT,PROCESS_LOG_STDERR
environment=TRANSPORT="vsock",LOG_VSOCK_CID="3",LOG_VSOCK_PORT="8001"
; environment=TRANSPORT="tcp",LOG_TCP_HOST="127.0.0.1",LOG_TCP_PORT="1514"
autorestart=true
buffer_size=200
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface
